### ISSUE TITLE
Not really a issue, but a question.

### ISSUE THREAD

**Issue by Clu3l3s3** [yogurtsyum/qbot#33] opened 2020-09-03 12:19 UTC
Is it possible it possible to.get your status saying Members: #... Servers #... Using thr rval command? If so can you tell me how

**Comment by TypicallyShad** [comment] 2020-09-03 16:13
Hey there!

This is not the place to ask for code, it certainly is possible but we do not provide support for this. If you are wanting to do this, please look at [their issue tab/support team.](https://github.com/discordjs/discord.js/). We apologize for any issues caused by this.

Our server will hopefully be reopening again soon to the public and we will provide channels there for bot development, we'll be excited to see you again soon.

If you do not have any other questions/issues, please close this.

**Closed** 2020-09-03 17:55 UTC
